$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)

PRODUCT_DEVICE := TECNO-KH6
PRODUCT_NAME := twrp_TECNO-KH6
PRODUCT_BRAND := TECNO
PRODUCT_MODEL := TECNO KH6
PRODUCT_MANUFACTURER := TECNO

PRODUCT_USE_DYNAMIC_PARTITIONS := true
PRODUCT_BUILD_SUPER_PARTITION := false
